project_id = "yqjugovqhvxoxvrceqqp"

[functions.get-member-tasks]
verify_jwt = false

[functions.get-monday-users]
verify_jwt = false

[functions.get-board-view-data]
verify_jwt = false

[functions.invite-member]
verify_jwt = false

[functions.activate-invited-member]
verify_jwt = false

[functions.execute-workflow]
verify_jwt = false

[functions.reset-member-password]
verify_jwt = false
