project_id = "yqjugovqhvxoxvrceqqp"

[api]
enabled = true

[functions.get-member-tasks]
enabled = true
verify_jwt = false

[functions.send-invite-email]
enabled = true
verify_jwt = false

[functions.auth-email-hook]
enabled = true
verify_jwt = false

[functions.invite-member]
enabled = true
verify_jwt = false
